version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=3 --threads=2 --bind 0.0.0.0:8000 django_settings.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: "visions"
      POSTGRES_USER: "olesya"
      POSTGRES_PASSWORD: "secure_password"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "visions"
      POSTGRES_USER: "olesya"
      POSTGRES_PASSWORD: "secure_password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
