# Generated by Django 5.1.5 on 2025-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_task_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
    ]
