# Generated by Django 5.1.5 on 2025-02-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_task_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='in_process',
            field=models.BooleanField(default=True),
        ),
    ]
