# Generated by Django 5.1.5 on 2025-02-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_task_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recipient_email',
            field=models.EmailField(default='sarsendimas@gmail.com', max_length=254),
        ),
    ]
