# Generated by Django 5.1.5 on 2025-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_task_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extended_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('process', 'В процессе выполнения'), ('completed', 'Одобрено'), ('rejected', 'Отклонено'), ('overdue', 'Просрочено'), ('deadline_extended', 'Срок продлен')], default='pending', max_length=20),
        ),
    ]
