# Generated by Django 5.1.5 on 2025-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_task_extended_deadline_task_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_former_user',
            field=models.BooleanField(default=False),
        ),
    ]
