# Generated by Django 5.1.5 on 2025-09-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_profile_is_former_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
