# Generated by Django 5.1.5 on 2025-10-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_task_penalty_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='tasks1/'),
        ),
    ]
