# Generated by Django 5.1.5 on 2025-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_alter_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user_response_file',
            field=models.FileField(blank=True, null=True, upload_to='tasks1/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='tasks/'),
        ),
    ]
