# Generated by Django 5.1.5 on 2025-10-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_task_user_file_path_task_user_response_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_file_path',
        ),
    ]
