# Generated by Django 5.1.5 on 2025-10-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_remove_task_user_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('process', 'В процессе выполнения'), ('completed', 'Одобрено'), ('rejected', 'Отклонено'), ('overdue', 'Просрочено'), ('deadline_extended', 'Срок продлен')], default='process', max_length=20),
        ),
    ]
